export const siteConfig = {
  companyName: 'StoopidCartoons',
  siteUrl: 'https://stoopidcartoons.com',
  defaultLocale: 'en',
  email: 'stoopidcartoons@gmail.com',
  googlePlayDeveloperUrl: 'https://play.google.com/store/apps/dev?id=9103063599459576814',
  xUrl: 'https://x.com/St00pidCart00ns',
  instagramUrl: 'https://www.instagram.com/st00pid_cart00ns/',
  tiktokUrl: 'https://www.tiktok.com/@stoopidcartoons',
  youtubeUrl: 'https://www.youtube.com/@St00pidCart00ns',
  facebookUrl: 'https://www.facebook.com/StoopidCartoons/',
  socialImagePath: '/social-preview.png',
  themeColor: '#0f0f0f',
  accentColor: '#e50914',
};
